version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sistema_estacionamento
    volumes:
      - .:/var/www/html
    networks:
      - laravel_network
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_HOST=db
      - DB_DATABASE=estacionamento
      - DB_USERNAME=estacionamento
      - DB_PASSWORD=123456

  web:
    image: nginx:latest
    container_name: laravel_estac
    ports:
      - "2020:80"
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel_network
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: sis_estacionamento_db
    environment:
      - MYSQL_DATABASE=estacionamento
      - MYSQL_USER=estacionamento
      - MYSQL_PASSWORD=123456
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laravel_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7.2
    container_name: estacionamento_redis
    networks:
      - laravel_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2.1
    container_name: estacionamento_phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: estacionamento
      PMA_PASSWORD: 123456
    ports:
      - "2030:80"
    depends_on:
      - db
    networks:
      - laravel_network

volumes:
  db_data:

networks:
  laravel_network:
    driver: bridge
